name: Test Coverage

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main ]
  # Don't run on tags since build-releases.yml handles that

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    # Skip if this is a tag push (releases handle their own testing)
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxcb-cursor0 libgl1-mesa-dev libegl1-mesa-dev libxrandr2 libxss1 libxcursor1 libxcomposite1 libasound2t64 libxi6 libxtst6 xvfb
        # Additional GUI testing dependencies
        sudo apt-get install -y libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0
    
    - name: Install uv
      run: pip install uv
    
    - name: Install dependencies
      run: uv sync --extra test --extra gpu
    
    - name: Run basic tests with coverage
      run: |
        export QT_QPA_PLATFORM=offscreen
        uv run pytest tests/test_minimal.py tests/test_init.py --cov=src/oopsie_daisy --cov-report=xml --cov-report=term-missing --cov-report=html:htmlcov
    
    - name: Run GUI tests (cross-platform validation)
      run: |
        export QT_QPA_PLATFORM=offscreen
        export DISPLAY=:99.0
        # Start virtual display for GUI tests
        xvfb-run -a -s "-screen 0 1920x1080x24" uv run pytest tests/test_gui_functionality.py tests/test_gui_visual.py -v --tb=short
      continue-on-error: true  # Don't fail the entire build if GUI tests have issues
    
    - name: Upload coverage reports as artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-report
        path: |
          coverage.xml
          htmlcov/
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      if: always()
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false