name: Test Coverage

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main ]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install uv
      run: pip install uv
    
    - name: Install dependencies
      run: uv sync --extra test --extra gpu
    
    - name: Run tests with coverage
      run: |
        uv run pytest tests/test_cross_platform.py tests/test_init.py tests/test_hardware_monitor.py --cov=src/oopsie_daisy --cov-report=xml --cov-report=term-missing --cov-report=html:htmlcov
    
    - name: Upload coverage reports as artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-report
        path: |
          coverage.xml
          htmlcov/
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      if: always()
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false